export const iphonePro12 = {
    'technology': 'GSM / CDMA / HSPA / EVDO / LTE / 5G',	
    'announced': '2020 Octover 13th',
    'status': 'available',
    'dimensions': '146.7 x 71.5 x 7.4 mm (5.78 x 2.81 x 0.29 in)',
    'weight': '189g',
    'build': 'Glass front (Corning-made glass), glass back (Corning-made glass), stainless steel frame',
    'sim': 'Nano-SIM and eSIM or Dual SIM (Nano-SIM, dual stand-by) - for China',
    'size': '6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio)',
    'protection': 'Ceramic Shield glass',
    'memory': 'card slot no',
    'mainCamera': '12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS',
    'video': '4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to 60fps), stereo sound rec.',
    'sound': 'Loudspeaker	Yes, with stereo speakers',
    'bluetooth': '5.0, A2DP, LE',
    'positioning':	'GPS, GLONASS, GALILEO, QZSS',
    'nfc': 'Yes',
    'radio': 'No',
    'usbLighting': 'USB 2.0',
};
